"use client";

import {AnimatePresence,motion} from "framer-motion";
import {ArrowDown,ArrowUpRight,Headphones,Languages,Menu,Moon,Sun,X} from "lucide-react";
import {useEffect,useState} from "react";
import {copy,projects,type Locale} from "@/lib/i18n";

type Theme="dark"|"light";
function Reveal({children,delay=0,className=""}:{children:React.ReactNode;delay?:number;className?:string}){return <motion.div className={className} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.7,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Avatar({label}:{label:string}){return <motion.div initial={{opacity:0,scale:.94,rotate:-2}} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:.8,ease:[.22,1,.36,1]}} className="avatar-shell relative mx-auto aspect-square w-full max-w-[280px] overflow-hidden rounded-[2.5rem]" role="img" aria-label={label}><div className="absolute inset-[20%]"><div className="avatar-hoodie absolute inset-x-[-12%] bottom-[-4%]"><div className="avatar-hood"/></div><div className="avatar-head absolute left-[18%] right-[18%] top-[12%] aspect-[.82]"><div className="avatar-hair"/><div className="avatar-ear left"/><div className="avatar-ear right"/><div className="avatar-eye left"/><div className="avatar-eye right"/><div className="avatar-beard"/><div className="avatar-mouth"/><div className="avatar-headphones"/><div className="avatar-cup left"/><div className="avatar-cup right"/></div></div><div className="absolute bottom-5 left-6 font-mono text-[9px] uppercase tracking-[.2em] text-[var(--faint)]">FS / Dublin</div><Headphones className="absolute right-6 top-6 text-[var(--faint)]" size={17}/></motion.div>}

export default function Home(){
 const[locale,setLocale]=useState<Locale>("en");const[theme,setTheme]=useState<Theme>("dark");const[open,setOpen]=useState(false);const t=copy[locale];
 useEffect(()=>{const l=window.localStorage.getItem("portfolio-locale");const th=window.localStorage.getItem("portfolio-theme");if(l==="en"||l==="pt")setLocale(l);if(th==="dark"||th==="light")setTheme(th)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.lang=locale;window.localStorage.setItem("portfolio-theme",theme);window.localStorage.setItem("portfolio-locale",locale)},[locale,theme]);
 const toggleLocale=()=>setLocale(v=>v==="en"?"pt":"en");const toggleTheme=()=>setTheme(v=>v==="dark"?"light":"dark");
 const navItems=[["journey","#journey",t.nav.journey],["work","#work",t.nav.work],["about","#about",t.nav.about],["contact","#contact",t.nav.contact]] as const;
 return <main id="top" className="overflow-hidden bg-[var(--bg)] text-[var(--fg)] transition-colors duration-500">
  <header className="fixed inset-x-0 top-0 z-50 px-4 py-4 md:px-8"><div className="mx-auto flex max-w-[1400px] items-center justify-between rounded-full border border-[var(--line)] bg-[color-mix(in_srgb,var(--bg)_78%,transparent)] px-4 py-3 backdrop-blur-xl md:px-5"><a href="#top" className="font-mono text-xs tracking-[.22em]">FS<span className="text-[var(--faint)]">/26</span></a><nav className="hidden items-center gap-6 md:flex">{navItems.map(([key,href,label])=><a key={key} href={href} className="text-sm text-[var(--muted)] transition-colors hover:text-[var(--fg)]">{label}</a>)}<button type="button" onClick={toggleLocale} className="flex items-center gap-1.5 text-sm text-[var(--muted)] hover:text-[var(--fg)]" aria-label={t.controls.language}><Languages size={15}/>{locale==="en"?"PT":"EN"}</button><button type="button" onClick={toggleTheme} className="flex items-center gap-1.5 text-sm text-[var(--muted)] hover:text-[var(--fg)]" aria-label={t.controls.theme}>{theme==="dark"?<Sun size={15}/>:<Moon size={15}/>} {theme==="dark"?t.controls.light:t.controls.dark}</button><a href="mailto:hello@felipeseabra.dev" className="flex items-center gap-1 text-sm">{t.nav.talk}<ArrowUpRight size={14}/></a></nav><button type="button" aria-label={open?t.controls.menuClose:t.controls.menuOpen} onClick={()=>setOpen(!open)} className="md:hidden">{open?<X size={20}/>:<Menu size={20}/>}</button></div><AnimatePresence>{open&&<motion.nav initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} className="mx-auto mt-2 rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-2xl md:hidden">{navItems.map(([key,href,label])=><a onClick={()=>setOpen(false)} key={key} href={href} className="block border-b border-[var(--line)] py-4 text-lg">{label}</a>)}<div className="flex gap-3 pt-5"><button type="button" onClick={toggleLocale} className="rounded-full border border-[var(--line)] px-4 py-2 text-xs">{locale==="en"?"Português":"English"}</button><button type="button" onClick={toggleTheme} className="rounded-full border border-[var(--line)] px-4 py-2 text-xs">{theme==="dark"?t.controls.light:t.controls.dark}</button></div></motion.nav>}</AnimatePresence></header>

  <section className="relative flex min-h-screen items-end px-5 pb-12 pt-32 md:px-8 md:pb-16"><div className="glow absolute inset-0"/><div className="grid-lines absolute inset-0 opacity-60"/><div className="noise absolute inset-0 opacity-[.12]"/><div className="relative mx-auto grid w-full max-w-[1400px] gap-12 lg:grid-cols-[1fr_300px] lg:items-end"><div><div className="mb-9 flex flex-wrap justify-between gap-4 font-mono text-[10px] uppercase tracking-[.2em] text-[var(--faint)]"><span>{t.hero.location}</span><span>{t.hero.eyebrow}</span></div><motion.h1 initial={{opacity:0,y:60}} animate={{opacity:1,y:0}} transition={{duration:1,ease:[.22,1,.36,1]}} className="max-w-6xl text-[14vw] font-medium leading-[.78] tracking-[-.09em] md:text-[11.5vw]">Felipe<br/><span className="ml-[8vw] text-[var(--faint)]">Seabra.</span></motion.h1><div className="mt-12 grid gap-8 md:grid-cols-[1fr_360px]"><p className="max-w-2xl text-lg leading-7 text-[var(--muted)] md:text-xl">{t.hero.title}</p><div><p className="mb-5 max-w-sm text-sm leading-6 text-[var(--muted)]">{t.hero.intro}</p><a href="#journey" className="inline-flex items-center gap-3 font-mono text-xs uppercase tracking-[.18em]"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-[var(--line)]"><ArrowDown size={15}/></span>{t.hero.cta}</a></div></div></div><Avatar label={t.avatar}/></div></section>

  <section id="journey" className="border-y border-[var(--line)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1400px]"><Reveal><div className="mb-20 max-w-3xl"><span className="font-mono text-xs uppercase tracking-[.2em] text-[var(--faint)]">{t.timeline.label}</span><h2 className="mt-5 text-5xl tracking-[-.06em] md:text-8xl">{t.timeline.title}</h2><p className="mt-7 max-w-2xl text-base leading-7 text-[var(--muted)] md:text-lg">{t.timeline.intro}</p></div></Reveal><div className="relative"><div className="timeline-line absolute bottom-0 left-[11px] top-0 w-px md:left-1/2"/>{t.timeline.entries.map((entry,index)=><Reveal key={entry.chapter} delay={index*.05} className="relative mb-16 last:mb-0 md:mb-24"><div className="grid gap-8 md:grid-cols-2 md:gap-20"><div className={index%2===0?"md:pr-20":"md:order-2 md:pl-20"}><div className="relative pl-10 md:pl-0"><div className="timeline-dot absolute left-[-1px] top-1 h-6 w-6 rounded-full md:hidden"/><span className="font-mono text-[10px] uppercase tracking-[.2em] text-[var(--faint)]">{entry.period}</span><h3 className="mt-3 text-3xl tracking-[-.04em] md:text-5xl">{entry.title}</h3></div></div><div className={index%2===0?"md:pl-20":"md:order-1 md:pr-20"}><div className="relative pl-10 md:pl-0"><div className="timeline-dot absolute left-[-1px] top-1 hidden h-6 w-6 rounded-full md:block"/><p className="max-w-xl text-base leading-7 text-[var(--muted)]">{entry.body}</p><div className="mt-6 flex flex-wrap gap-2">{entry.tags.map(tag=><span key={tag} className="rounded-full border border-[var(--line)] px-3 py-1.5 font-mono text-[9px] uppercase tracking-[.12em] text-[var(--faint)]">{tag}</span>)}</div></div></div></div></Reveal>)}</div></div></section>

  <section id="work" className="px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1400px]"><Reveal><div className="mb-14 max-w-3xl"><span className="font-mono text-xs uppercase tracking-[.2em] text-[var(--faint)]">{t.work.label}</span><h2 className="mt-5 text-5xl tracking-[-.06em] md:text-8xl">{t.work.title}</h2><p className="mt-7 text-base leading-7 text-[var(--muted)] md:text-lg">{t.work.intro}</p></div></Reveal>{projects.map((project,index)=><Reveal key={project.number} delay={index*.05}><motion.a href={project.href} whileHover={{x:6}} transition={{duration:.25}} className="group grid gap-5 border-t border-[var(--line)] py-8 md:grid-cols-[70px_1fr_280px_70px] md:items-center"><span className="font-mono text-xs text-[var(--faint)]">{project.number}</span><div><span className="text-xs uppercase tracking-[.18em] text-[var(--faint)]">{project.category}</span><h3 className="mt-2 text-3xl tracking-[-.04em] md:text-5xl">{project.title}</h3><div className="mt-5 flex flex-wrap gap-2">{project.stack.map(tag=><span key={tag} className="font-mono text-[9px] text-[var(--faint)]">{tag}</span>)}</div></div><p className="text-sm leading-6 text-[var(--muted)]">{project.description}</p><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[var(--line)] transition-transform duration-300 group-hover:rotate-45"><ArrowUpRight size={17}/></span></motion.a></Reveal>)}</div></section>

  <section id="about" className="border-t border-[var(--line)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-[1400px] gap-14 md:grid-cols-[.65fr_1.35fr]"><Reveal><span className="font-mono text-xs uppercase tracking-[.2em] text-[var(--faint)]">{t.about.label}</span></Reveal><Reveal><p className="text-3xl leading-[1.08] tracking-[-.05em] md:text-6xl">{t.about.title}</p><p className="mt-10 max-w-2xl text-base leading-7 text-[var(--muted)] md:text-lg">{t.about.body}</p><div className="mt-10 inline-flex rounded-full border border-[var(--line)] px-4 py-2 font-mono text-[10px] uppercase tracking-[.15em] text-[var(--faint)]">{t.about.experience}</div></Reveal></div></section>
  <section className="px-5 pb-24 md:px-8 md:pb-36"><div className="mx-auto grid max-w-[1400px] gap-5 md:grid-cols-2 lg:grid-cols-4">{t.capabilities.map((skill,index)=><Reveal key={skill} delay={index*.04}><div className="border-t border-[var(--line)] pt-5"><span className="font-mono text-[10px] text-[var(--faint)]">0{index+1}</span><p className="mt-7 text-lg text-[var(--muted)]">{skill}</p></div></Reveal>)}</div></section>
  <section id="contact" className="relative border-t border-[var(--line)] px-5 py-28 md:px-8 md:py-44"><div className="glow absolute inset-0"/><div className="noise absolute inset-0 opacity-[.08]"/><div className="relative mx-auto max-w-[1400px]"><Reveal><span className="font-mono text-xs uppercase tracking-[.2em] text-[var(--faint)]">{t.contact.label}</span><h2 className="mt-8 max-w-6xl text-[13vw] font-medium leading-[.8] tracking-[-.09em] md:text-[9vw]">{t.contact.title}</h2><p className="mt-10 max-w-xl text-base leading-7 text-[var(--muted)] md:text-lg">{t.contact.body}</p></Reveal><Reveal delay={.08}><a href="mailto:hello@felipeseabra.dev" className="mt-10 inline-flex items-center gap-3 text-xl transition-opacity hover:opacity-60 md:text-2xl">{t.contact.cta}<ArrowUpRight size={19}/></a></Reveal></div></section>
  <footer className="border-t border-[var(--line)] px-5 py-7 md:px-8"><div className="mx-auto flex max-w-[1400px] flex-wrap justify-between gap-3 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--faint)]"><span>© {new Date().getFullYear()} Felipe Seabra</span><span>Dublin / Ireland</span><span>Next.js / TypeScript</span></div></footer>
 </main>;
}